# Generated by Django 4.2.20 on 2025-04-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("completion", "0003_learning_context"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="blockcompletion",
            new_name="completion__user_id_861fe5_idx",
            old_fields=("user", "context_key", "modified"),
        ),
        migrations.RenameIndex(
            model_name="blockcompletion",
            new_name="completion__course__c6e6ad_idx",
            old_fields=("context_key", "block_type", "user"),
        ),
    ]
